"""Deterministic benefit arithmetic.

This module is money. Nothing here is generated by a model, and nothing here
is imported from anywhere that talks to a model.

Tests for this module were written before the implementation. If you change a
function here, change the test first.

Owner: Bikram Bhattarai. Reviewer: Aayush Khade.
"""

from __future__ import annotations

import csv
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from oshc.schemas import BenefitRule

ABSTAIN_WORDING = "Medibank confirms your exact benefit."


def _money(value: float | Decimal) -> Decimal:
    """Round to cents, half up. Never use float arithmetic on money."""
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def load_rules(path: str | Path) -> dict[str, BenefitRule]:
    """Load the benefit rules table. Keyed by category."""
    rules: dict[str, BenefitRule] = {}
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            row = {k: (v.strip() if isinstance(v, str) else v) for k, v in row.items()}
            value = row.get("value") or None
            rule = BenefitRule(
                category=row["category"],
                description=row["description"],
                benefit_basis=row["benefit_basis"],
                value=float(value) if value else None,
                pds_page=row["pds_page"],
                captured_on=row["captured_on"],
            )
            rules[rule.category] = rule
    return rules


def expected_benefit(
    rule: BenefitRule | None,
    charged: Decimal | float,
    schedule_fee: Decimal | float | None = None,
) -> Decimal | None:
    """Return the benefit the PDS states, or None to abstain.

    Abstain cases, all of which must return None rather than a guess:
      - no rule for the category
      - the rule itself is an abstain rule
      - percent_of_mbs with no schedule fee available
    """
    if rule is None or rule.benefit_basis == "abstain" or rule.value is None:
        return None

    charged_d = _money(charged)

    if rule.benefit_basis == "fixed":
        benefit = _money(rule.value)
    elif rule.benefit_basis == "percent_of_charge":
        benefit = _money(charged_d * Decimal(str(rule.value)) / Decimal("100"))
    elif rule.benefit_basis == "percent_of_mbs":
        if schedule_fee is None:
            return None
        benefit = _money(_money(schedule_fee) * Decimal(str(rule.value)) / Decimal("100"))
    else:
        return None

    # A benefit never exceeds what was actually charged.
    return min(benefit, charged_d)


def gap(charged: Decimal | float, benefit: Decimal | float | None) -> Decimal | None:
    """Out of pocket amount. None when the benefit is unknown."""
    if benefit is None:
        return None
    result = _money(charged) - _money(benefit)
    return max(result, Decimal("0.00"))
